### ISSUE TITLE
来加友链了

### ISSUE THREAD

**Issue by coderiy** [f2h2h1/f2h2h1.github.io#1]
已添加贵站
网站名称：Barney’s Blog
网站地址：https://hugo.bnblogs.cc/
网站头像：https://hugo.bnblogs.cc/images/img/20220215001349.png
网站描述：All the truth is simple
网站 RSS 地址(可选): https://hugo.bnblogs.cc/index.xml

**Comment by f2h2h1** [comment]
已添加
