### ISSUE TITLE
龙年好，基于三年前的设想刚搭的博客聚合演示

### ISSUE THREAD

**Issue by nobodxbodon** [f2h2h1/f2h2h1.github.io#4]
基于 [设想](https://gitee.com/zhishi/collection-of-chinese-blogs/)，刚用gh pages搭了 [这个演示](http://nobodxbodon.github.io/)。博客同步、索引和网页内容生成等源码都 [在此](https://gitee.com/zhishi/collection-of-chinese-blogs/tree/master/%E5%8E%9F%E5%9E%8B)。
现在仅有最基本的浏览功能，部分原文 url [还需要修](https://gitee.com/zhishi/collection-of-chinese-blogs/issues/I94K59)。
打算尽量定期更新内容并补充功能。
刚加了您的仓库入内置仓库列表。
欢迎任何建议意见！

**Comment by f2h2h1** [comment]
已添加友链

**Comment by nobodxbodon** [comment]
非常感谢。阶段进展 [在此issue](https://github.com/nobodxbodon/nobodxbodon.github.io/issues/1) 报告，欢迎订阅。
